
pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                dir('week3/dev-ops/transfer-service') {
                    sh './mvnw clean compile'
                }
            }
        }
        stage('Test') {
            steps {
                dir('week3/dev-ops/transfer-service') {
                    sh './mvnw test'
                }
            }
        }

        stage('Static Code Analysis') {
            steps {
                dir('week3/dev-ops/transfer-service') {
                    sh "./mvnw sonar:sonar -Dsonar.projectKey=transfer-service -Dsonar.host.url=http://localhost:9000 -Dsonar.login=sqa_129a873e79f45ac95bde1296b36900946d5ce958"
                }
            }
        }

        // wait, once sonaqube, passed quality-gates..

        stage('Package') {
            steps {
                dir('week3/dev-ops/transfer-service') {
                    sh './mvnw package -DskipTests'
                }
            }
        }
    }
}